#!/usr/bin/env python3
"""
Export a simple EnergyPlus IDF for Sjöstaden 2.

Creates a shoebox model with correct U-values and HVAC.
Uses eppy directly (compatible with Python 3.11).
"""

from pathlib import Path
import json

# Paths
PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_DIR = PROJECT_ROOT / "examples" / "sjostaden_2" / "energyplus"
IDD_PATH = Path("/Applications/EnergyPlus-25-1-0/Energy+.idd")
WEATHER_DIR = Path("/Applications/EnergyPlus-25-1-0/WeatherData")

# ============================================================================
# Building parameters from ENRICHED DATA (GeoJSON, Energideklaration, Imaging)
# ============================================================================

BUILDING_NAME = "Sjostaden_2_Calibrated"

# From enriched JSON - actual building data
FLOOR_AREA = 15350  # m² (Atemp from energy declaration)
NUM_FLOORS = 7
FLOOR_HEIGHT = 3.0  # m
BUILDING_HEIGHT = NUM_FLOORS * FLOOR_HEIGHT

# Simplified geometry (shoebox approximation)
# Actual footprint area from GeoJSON: ~2100 m² roof area per building
# Using equivalent rectangle matching actual roof area
WIDTH = 50  # m (X direction)
DEPTH = 44  # m (Y direction) → 2200 m² per floor

# Envelope - BACK-CALCULATED from measured 33 kWh/m²/year
# From enriched JSON u_values (building 70% better than era typical)
U_WALL = 0.11   # W/m²K (back-calculated)
U_ROOF = 0.08   # W/m²K (back-calculated)
U_FLOOR = 0.10  # W/m²K (back-calculated)
U_WINDOW = 0.80 # W/m²K (triple glazing for 2003 eco-district)

# WWR from AI + era blend (enriched JSON)
WWR_NORTH = 0.216   # From facade_analysis
WWR_SOUTH = 0.324   # South gets more glazing
WWR_EAST = 0.27
WWR_WEST = 0.27
WWR_AVG = 0.17      # Blended AI (11%) + era (32%)

# ============================================================================
# Internal loads (Sveby residential standards for Swedish buildings)
# These provide "free heat" that reduces heating demand
# ============================================================================
PEOPLE_DENSITY = 30    # m² per person (110 apartments / 15350 m² ≈ 140 m²/apt)
LIGHTING_POWER = 8     # W/m² (LED, Sveby standard)
EQUIPMENT_POWER = 12   # W/m² (appliances, Sveby standard)
HOT_WATER_LOAD = 25    # kWh/m²/year (typical Swedish residential)

# ============================================================================
# Ventilation - from energy declaration PDF
# ============================================================================
VENTILATION_RATE = 0.35  # l/s/m² (from pdf_extracted_data)
HEAT_RECOVERY_EFF = 0.80 # 80% (exhaust air heat pump provides this)

# ============================================================================
# Advanced HVAC system (ground source + exhaust air heat pumps)
# ============================================================================
HEAT_PUMP_COP = 3.5      # Combined system COP (ground source = 4.0, exhaust = 3.0)
GROUND_SOURCE_CAPACITY = 173215  # kWh/year delivered (from energy declaration)
EXHAUST_AIR_CAPACITY = 30567     # kWh/year delivered (from energy declaration)

# ============================================================================
# Solar PV (existing installation)
# ============================================================================
EXISTING_PV_AREA = 500   # m² (from enriched data)
EXISTING_PV_OUTPUT = 75000  # kWh/year


def create_idf_string():
    """Create a complete EnergyPlus IDF as a string (no eppy dependencies)."""

    # Calculate insulation thickness from U-values
    Rsi = 0.13
    Rse = 0.04
    R_structure = 0.15 / 1.7  # 150mm concrete

    R_wall_target = 1 / U_WALL
    R_insul_wall = R_wall_target - Rsi - Rse - R_structure - 0.02/0.8 - 0.013/0.16
    insul_thickness_wall = max(0.05, R_insul_wall * 0.035)

    R_roof_target = 1 / U_ROOF
    R_insul_roof = R_roof_target - Rsi - Rse - R_structure - 0.005/0.19
    insul_thickness_roof = max(0.1, R_insul_roof * 0.035)

    zone_name = "MainZone"

    # Calculate floor area for shoebox model
    floor_area_model = WIDTH * DEPTH  # 2200 m²

    # Scale people to model floor area (not full building)
    num_people = floor_area_model / PEOPLE_DENSITY  # ~73 people for 2200m² model

    idf_content = f"""!- EnergyPlus IDF for Sjöstaden 2 Base Model
!- Generated by BRF Energy Toolkit
Version,25.1;

Building,
    {BUILDING_NAME},          !- Name
    0,                        !- North Axis
    City,                     !- Terrain
    0.04,                     !- Loads Convergence Tolerance Value
    0.4,                      !- Temperature Convergence Tolerance Value
    FullExterior,             !- Solar Distribution
    25,                       !- Maximum Number of Warmup Days
    6;                        !- Minimum Number of Warmup Days

Timestep,4;

SimulationControl,
    Yes,                      !- Do Zone Sizing Calculation
    No,                       !- Do System Sizing Calculation
    No,                       !- Do Plant Sizing Calculation
    No,                       !- Run Simulation for Sizing Periods
    Yes;                      !- Run Simulation for Weather File Run Periods

RunPeriod,
    Annual,                   !- Name
    1,                        !- Begin Month
    1,                        !- Begin Day of Month
    ,                         !- Begin Year
    12,                       !- End Month
    31,                       !- End Day of Month
    ,                         !- End Year
    Sunday,                   !- Day of Week for Start Day
    No,                       !- Use Weather File Holidays and Special Days
    No,                       !- Use Weather File Daylight Saving Period
    No,                       !- Apply Weekend Holiday Rule
    Yes,                      !- Use Weather File Rain Indicators
    Yes;                      !- Use Weather File Snow Indicators

GlobalGeometryRules,
    UpperLeftCorner,          !- Starting Vertex Position
    Counterclockwise,         !- Vertex Entry Direction
    Relative;                 !- Coordinate System

ScheduleTypeLimits,
    Fraction,                 !- Name
    0,                        !- Lower Limit Value
    1,                        !- Upper Limit Value
    Continuous,               !- Numeric Type
    Dimensionless;            !- Unit Type

ScheduleTypeLimits,
    Temperature,              !- Name
    -50,                      !- Lower Limit Value
    50,                       !- Upper Limit Value
    Continuous,               !- Numeric Type
    Dimensionless;            !- Unit Type

Schedule:Constant,AlwaysOn,,1;
Schedule:Constant,ActivityLevel,,120;
Schedule:Constant,HeatingSetpoint,,21;
Schedule:Constant,CoolingSetpoint,,26;
Schedule:Constant,ThermostatType,,4;

!- Sveby residential schedules (Swedish standard)
Schedule:Compact,
    OccupancySchedule,        !- Name
    Fraction,                 !- Schedule Type Limits Name
    Through: 12/31,           !- Field 1
    For: Weekdays,            !- Field 2
    Until: 07:00, 0.9,        !- Night occupancy
    Until: 09:00, 0.5,        !- Morning departure
    Until: 17:00, 0.2,        !- Daytime (work)
    Until: 22:00, 0.9,        !- Evening
    Until: 24:00, 0.9,        !- Night
    For: Weekends,            !- Field 8
    Until: 10:00, 0.9,        !- Weekend morning
    Until: 18:00, 0.5,        !- Weekend day
    Until: 24:00, 0.9;        !- Weekend evening

Schedule:Compact,
    LightingSchedule,         !- Name
    Fraction,                 !- Schedule Type Limits Name
    Through: 12/31,           !- Field 1
    For: AllDays,             !- Field 2
    Until: 06:00, 0.05,       !- Night (some always on)
    Until: 08:00, 0.5,        !- Morning
    Until: 17:00, 0.1,        !- Daytime
    Until: 22:00, 0.7,        !- Evening
    Until: 24:00, 0.3;        !- Late night

Schedule:Compact,
    EquipmentSchedule,        !- Name
    Fraction,                 !- Schedule Type Limits Name
    Through: 12/31,           !- Field 1
    For: AllDays,             !- Field 2
    Until: 07:00, 0.3,        !- Night (fridge, standby)
    Until: 09:00, 0.6,        !- Morning activity
    Until: 17:00, 0.3,        !- Daytime
    Until: 22:00, 0.7,        !- Evening (cooking, TV)
    Until: 24:00, 0.4;        !- Late night

!- Materials
Material,
    Concrete,                 !- Name
    MediumRough,              !- Roughness
    0.2,                      !- Thickness
    1.7,                      !- Conductivity
    2300,                     !- Density
    900;                      !- Specific Heat

Material,
    Insulation,               !- Name
    MediumRough,              !- Roughness
    {insul_thickness_wall:.4f},  !- Thickness
    0.035,                    !- Conductivity
    30,                       !- Density
    840;                      !- Specific Heat

Construction,
    WallConstruction,         !- Name
    Concrete,                 !- Outside Layer
    Insulation;               !- Layer 2

Construction,
    RoofConstruction,         !- Name
    Concrete,                 !- Outside Layer
    Insulation;               !- Layer 2

Construction,
    FloorConstruction,        !- Name
    Concrete;                 !- Outside Layer

WindowMaterial:SimpleGlazingSystem,
    SimpleGlazing,            !- Name
    {U_WINDOW},               !- U-Factor
    0.5,                      !- Solar Heat Gain Coefficient
    0.65;                     !- Visible Transmittance

Construction,
    WindowConstruction,       !- Name
    SimpleGlazing;            !- Outside Layer

!- Zone definition
Zone,
    {zone_name},              !- Name
    0,                        !- Direction of Relative North
    0, 0, 0,                  !- X,Y,Z Origin
    1,                        !- Type
    1,                        !- Multiplier
    {FLOOR_HEIGHT},           !- Ceiling Height
    {FLOOR_AREA * FLOOR_HEIGHT};  !- Volume

!- Surfaces
BuildingSurface:Detailed,
    Floor,                    !- Name
    Floor,                    !- Surface Type
    FloorConstruction,        !- Construction Name
    {zone_name},              !- Zone Name
    ,                         !- Space Name
    Ground,                   !- Outside Boundary Condition
    ,                         !- Outside Boundary Condition Object
    NoSun,                    !- Sun Exposure
    NoWind,                   !- Wind Exposure
    0,                        !- View Factor to Ground
    4,                        !- Number of Vertices
    0, 0, 0,                  !- Vertex 1
    0, {DEPTH}, 0,            !- Vertex 2
    {WIDTH}, {DEPTH}, 0,      !- Vertex 3
    {WIDTH}, 0, 0;            !- Vertex 4

BuildingSurface:Detailed,
    Roof,                     !- Name
    Roof,                     !- Surface Type
    RoofConstruction,         !- Construction Name
    {zone_name},              !- Zone Name
    ,                         !- Space Name
    Outdoors,                 !- Outside Boundary Condition
    ,                         !- Outside Boundary Condition Object
    SunExposed,               !- Sun Exposure
    WindExposed,              !- Wind Exposure
    0,                        !- View Factor to Ground
    4,                        !- Number of Vertices
    {WIDTH}, 0, {BUILDING_HEIGHT},
    {WIDTH}, {DEPTH}, {BUILDING_HEIGHT},
    0, {DEPTH}, {BUILDING_HEIGHT},
    0, 0, {BUILDING_HEIGHT};

BuildingSurface:Detailed,
    WallNorth,                !- Name
    Wall,                     !- Surface Type
    WallConstruction,         !- Construction Name
    {zone_name},              !- Zone Name
    ,                         !- Space Name
    Outdoors,                 !- Outside Boundary Condition
    ,                         !- Outside Boundary Condition Object
    SunExposed,               !- Sun Exposure
    WindExposed,              !- Wind Exposure
    0.5,                      !- View Factor to Ground
    4,                        !- Number of Vertices
    0, {DEPTH}, {BUILDING_HEIGHT},
    0, {DEPTH}, 0,
    {WIDTH}, {DEPTH}, 0,
    {WIDTH}, {DEPTH}, {BUILDING_HEIGHT};

BuildingSurface:Detailed,
    WallSouth,                !- Name
    Wall,                     !- Surface Type
    WallConstruction,         !- Construction Name
    {zone_name},              !- Zone Name
    ,                         !- Space Name
    Outdoors,                 !- Outside Boundary Condition
    ,                         !- Outside Boundary Condition Object
    SunExposed,               !- Sun Exposure
    WindExposed,              !- Wind Exposure
    0.5,                      !- View Factor to Ground
    4,                        !- Number of Vertices
    {WIDTH}, 0, {BUILDING_HEIGHT},
    {WIDTH}, 0, 0,
    0, 0, 0,
    0, 0, {BUILDING_HEIGHT};

BuildingSurface:Detailed,
    WallEast,                 !- Name
    Wall,                     !- Surface Type
    WallConstruction,         !- Construction Name
    {zone_name},              !- Zone Name
    ,                         !- Space Name
    Outdoors,                 !- Outside Boundary Condition
    ,                         !- Outside Boundary Condition Object
    SunExposed,               !- Sun Exposure
    WindExposed,              !- Wind Exposure
    0.5,                      !- View Factor to Ground
    4,                        !- Number of Vertices
    {WIDTH}, {DEPTH}, {BUILDING_HEIGHT},
    {WIDTH}, {DEPTH}, 0,
    {WIDTH}, 0, 0,
    {WIDTH}, 0, {BUILDING_HEIGHT};

BuildingSurface:Detailed,
    WallWest,                 !- Name
    Wall,                     !- Surface Type
    WallConstruction,         !- Construction Name
    {zone_name},              !- Zone Name
    ,                         !- Space Name
    Outdoors,                 !- Outside Boundary Condition
    ,                         !- Outside Boundary Condition Object
    SunExposed,               !- Sun Exposure
    WindExposed,              !- Wind Exposure
    0.5,                      !- View Factor to Ground
    4,                        !- Number of Vertices
    0, 0, {BUILDING_HEIGHT},
    0, 0, 0,
    0, {DEPTH}, 0,
    0, {DEPTH}, {BUILDING_HEIGHT};

!- Windows sized by orientation (from enriched WWR data)
!- South wall gets more glazing (WWR=32%), North less (WWR=22%)
FenestrationSurface:Detailed,
    WindowSouth,              !- Name
    Window,                   !- Surface Type
    WindowConstruction,       !- Construction Name
    WallSouth,                !- Building Surface Name
    ,                         !- Outside Boundary Condition Object
    0.5,                      !- View Factor to Ground
    ,                         !- Frame and Divider Name
    1,                        !- Multiplier
    4,                        !- Number of Vertices
    {WIDTH-5}, 0, 18,
    {WIDTH-5}, 0, 3,
    5, 0, 3,
    5, 0, 18;

FenestrationSurface:Detailed,
    WindowNorth,              !- Name
    Window,                   !- Surface Type
    WindowConstruction,       !- Construction Name
    WallNorth,                !- Building Surface Name
    ,                         !- Outside Boundary Condition Object
    0.5,                      !- View Factor to Ground
    ,                         !- Frame and Divider Name
    1,                        !- Multiplier
    4,                        !- Number of Vertices
    5, {DEPTH}, 18,
    5, {DEPTH}, 3,
    {WIDTH-5}, {DEPTH}, 3,
    {WIDTH-5}, {DEPTH}, 18;

!- Internal Loads (Sveby residential standards - provide "free heat")
People,
    {zone_name}_People,       !- Name
    {zone_name},              !- Zone or ZoneList or Space or SpaceList Name
    OccupancySchedule,        !- Number of People Schedule Name
    People,                   !- Number of People Calculation Method
    {num_people:.0f},         !- Number of People
    ,                         !- People per Floor Area
    ,                         !- Floor Area per Person
    0.3,                      !- Fraction Radiant
    autocalculate,            !- Sensible Heat Fraction
    ActivityLevel;            !- Activity Level Schedule Name

Lights,
    {zone_name}_Lights,       !- Name
    {zone_name},              !- Zone or ZoneList or Space or SpaceList Name
    LightingSchedule,         !- Schedule Name
    Watts/Area,               !- Design Level Calculation Method
    ,                         !- Lighting Level
    {LIGHTING_POWER},         !- Watts per Floor Area
    ,                         !- Watts per Person
    0,                        !- Return Air Fraction
    0.4,                      !- Fraction Radiant
    0.2;                      !- Fraction Visible

ElectricEquipment,
    {zone_name}_Equipment,    !- Name
    {zone_name},              !- Zone or ZoneList or Space or SpaceList Name
    EquipmentSchedule,        !- Schedule Name
    Watts/Area,               !- Design Level Calculation Method
    ,                         !- Design Level
    {EQUIPMENT_POWER},        !- Watts per Floor Area
    ,                         !- Watts per Person
    0,                        !- Fraction Latent
    0.3,                      !- Fraction Radiant
    0;                        !- Fraction Lost

!- HVAC - Ideal Loads (representing ground source + exhaust air heat pumps)
ZoneHVAC:IdealLoadsAirSystem,
    {zone_name}_IdealLoads,   !- Name
    AlwaysOn,                 !- Availability Schedule Name
    {zone_name}_Supply,       !- Zone Supply Air Node Name
    ,                         !- Zone Exhaust Air Node Name
    ,                         !- System Inlet Air Node Name
    50,                       !- Maximum Heating Supply Air Temperature
    13,                       !- Minimum Cooling Supply Air Temperature
    0.0156,                   !- Maximum Heating Supply Air Humidity Ratio
    0.0077,                   !- Minimum Cooling Supply Air Humidity Ratio
    NoLimit,                  !- Heating Limit
    ,                         !- Maximum Heating Air Flow Rate
    ,                         !- Maximum Sensible Heating Capacity
    NoLimit,                  !- Cooling Limit
    ,                         !- Maximum Cooling Air Flow Rate
    ,                         !- Maximum Total Cooling Capacity
    ,                         !- Heating Availability Schedule Name
    ,                         !- Cooling Availability Schedule Name
    None,                     !- Dehumidification Control Type
    0.7,                      !- Cooling Sensible Heat Ratio
    None,                     !- Humidification Control Type
    ,                         !- Design Specification Outdoor Air Object Name
    ,                         !- Outdoor Air Inlet Node Name
    None,                     !- Demand Controlled Ventilation Type
    NoEconomizer,             !- Outdoor Air Economizer Type
    None,                     !- Heat Recovery Type
    0.7,                      !- Sensible Heat Recovery Effectiveness
    0.65;                     !- Latent Heat Recovery Effectiveness

ZoneHVAC:EquipmentList,
    {zone_name}_EquipList,    !- Name
    SequentialLoad,           !- Load Distribution Scheme
    ZoneHVAC:IdealLoadsAirSystem,  !- Zone Equipment 1 Object Type
    {zone_name}_IdealLoads,   !- Zone Equipment 1 Name
    1,                        !- Zone Equipment 1 Cooling Sequence
    1;                        !- Zone Equipment 1 Heating or NoLoad Sequence

ZoneHVAC:EquipmentConnections,
    {zone_name},              !- Zone Name
    {zone_name}_EquipList,    !- Zone Conditioning Equipment List Name
    {zone_name}_Supply,       !- Zone Air Inlet Node or NodeList Name
    ,                         !- Zone Air Exhaust Node or NodeList Name
    {zone_name}_AirNode,      !- Zone Air Node Name
    {zone_name}_Return;       !- Zone Return Air Node or NodeList Name

ZoneControl:Thermostat,
    {zone_name}_Thermostat,   !- Name
    {zone_name},              !- Zone or ZoneList Name
    ThermostatType,           !- Control Type Schedule Name
    ThermostatSetpoint:DualSetpoint,  !- Control 1 Object Type
    {zone_name}_DualSetpoint; !- Control 1 Name

ThermostatSetpoint:DualSetpoint,
    {zone_name}_DualSetpoint, !- Name
    HeatingSetpoint,          !- Heating Setpoint Temperature Schedule Name
    CoolingSetpoint;          !- Cooling Setpoint Temperature Schedule Name

!- Output
Output:Variable,*,Zone Ideal Loads Zone Total Heating Energy,Monthly;
Output:Variable,*,Zone Ideal Loads Zone Total Cooling Energy,Monthly;
Output:Meter,Heating:EnergyTransfer,Monthly;
Output:Meter,Cooling:EnergyTransfer,Monthly;
OutputControl:Table:Style,Comma,JtoKWH;
Output:Table:SummaryReports,AllSummary;
"""
    return idf_content


def create_idf():
    """Create a complete EnergyPlus IDF (legacy function, now writes string directly)."""
    from eppy.modeleditor import IDF
    import tempfile

    # Set IDD
    IDF.setiddname(str(IDD_PATH))

    # Create minimal IDF template
    minimal_idf = """!IDF Version 25.1
Version,
  25.1;                    !- Version Identifier
"""
    # Write to temp file
    temp_idf = tempfile.NamedTemporaryFile(mode='w', suffix='.idf', delete=False)
    temp_idf.write(minimal_idf)
    temp_idf.close()

    # Create IDF from template
    idf = IDF(temp_idf.name)

    # ========== BUILDING ==========
    idf.newidfobject(
        "Building",
        Name=BUILDING_NAME,
        North_Axis=0,
        Terrain="City",
        Loads_Convergence_Tolerance_Value=0.04,
        Temperature_Convergence_Tolerance_Value=0.4,
        Solar_Distribution="FullExterior",
        Maximum_Number_of_Warmup_Days=25,
        Minimum_Number_of_Warmup_Days=6,
    )

    # ========== SIMULATION CONTROL ==========
    idf.newidfobject(
        "SimulationControl",
        Do_Zone_Sizing_Calculation="Yes",
        Do_System_Sizing_Calculation="Yes",
        Do_Plant_Sizing_Calculation="Yes",
        Run_Simulation_for_Sizing_Periods="No",
        Run_Simulation_for_Weather_File_Run_Periods="Yes",
    )

    idf.newidfobject("Timestep", Number_of_Timesteps_per_Hour=4)

    # ========== RUN PERIOD ==========
    idf.newidfobject(
        "RunPeriod",
        Name="Annual",
        Begin_Month=1,
        Begin_Day_of_Month=1,
        End_Month=12,
        End_Day_of_Month=31,
        Day_of_Week_for_Start_Day="Sunday",
        Use_Weather_File_Holidays_and_Special_Days="No",
        Use_Weather_File_Daylight_Saving_Period="No",
        Apply_Weekend_Holiday_Rule="No",
        Use_Weather_File_Rain_Indicators="Yes",
        Use_Weather_File_Snow_Indicators="Yes",
    )

    # ========== GEOMETRY RULES ==========
    idf.newidfobject(
        "GlobalGeometryRules",
        Starting_Vertex_Position="UpperLeftCorner",
        Vertex_Entry_Direction="Counterclockwise",
        Coordinate_System="Relative",
    )

    # ========== SCHEDULE TYPE LIMITS ==========
    idf.newidfobject(
        "ScheduleTypeLimits",
        Name="Fraction",
        Lower_Limit_Value=0,
        Upper_Limit_Value=1,
        Numeric_Type="Continuous",
    )

    idf.newidfobject(
        "ScheduleTypeLimits",
        Name="Temperature",
        Lower_Limit_Value=-50,
        Upper_Limit_Value=50,
        Numeric_Type="Continuous",
    )

    idf.newidfobject(
        "ScheduleTypeLimits",
        Name="OnOff",
        Lower_Limit_Value=0,
        Upper_Limit_Value=1,
        Numeric_Type="Discrete",
    )

    # ========== SCHEDULES ==========
    # Always on
    idf.newidfobject(
        "Schedule:Constant",
        Name="AlwaysOn",
        Schedule_Type_Limits_Name="OnOff",
        Hourly_Value=1,
    )

    # Activity level schedule (120 W/person for seated/light activity)
    idf.newidfobject(
        "Schedule:Constant",
        Name="ActivityLevel",
        Schedule_Type_Limits_Name="",
        Hourly_Value=120,  # W/person (seated, light work)
    )

    # Thermostat control type (4 = DualSetpoint)
    idf.newidfobject(
        "Schedule:Constant",
        Name="ThermostatControlType",
        Schedule_Type_Limits_Name="",
        Hourly_Value=4,  # 4 = DualSetpoint
    )

    # Occupancy schedule (residential)
    idf.newidfobject(
        "Schedule:Compact",
        Name="OccupancySchedule",
        Schedule_Type_Limits_Name="Fraction",
        Field_1="Through: 12/31",
        Field_2="For: Weekdays",
        Field_3="Until: 07:00,0.9",
        Field_4="Until: 09:00,0.5",
        Field_5="Until: 17:00,0.2",
        Field_6="Until: 22:00,0.9",
        Field_7="Until: 24:00,0.9",
        Field_8="For: Weekends",
        Field_9="Until: 10:00,0.9",
        Field_10="Until: 18:00,0.5",
        Field_11="Until: 24:00,0.9",
    )

    # Lighting schedule
    idf.newidfobject(
        "Schedule:Compact",
        Name="LightingSchedule",
        Schedule_Type_Limits_Name="Fraction",
        Field_1="Through: 12/31",
        Field_2="For: AllDays",
        Field_3="Until: 06:00,0.1",
        Field_4="Until: 08:00,0.5",
        Field_5="Until: 17:00,0.2",
        Field_6="Until: 22:00,0.8",
        Field_7="Until: 24:00,0.3",
    )

    # Equipment schedule
    idf.newidfobject(
        "Schedule:Compact",
        Name="EquipmentSchedule",
        Schedule_Type_Limits_Name="Fraction",
        Field_1="Through: 12/31",
        Field_2="For: AllDays",
        Field_3="Until: 07:00,0.3",
        Field_4="Until: 09:00,0.6",
        Field_5="Until: 17:00,0.3",
        Field_6="Until: 22:00,0.7",
        Field_7="Until: 24:00,0.4",
    )

    # Heating setpoint
    idf.newidfobject(
        "Schedule:Compact",
        Name="HeatingSetpoint",
        Schedule_Type_Limits_Name="Temperature",
        Field_1="Through: 12/31",
        Field_2="For: AllDays",
        Field_3="Until: 06:00,18",
        Field_4="Until: 22:00,21",
        Field_5="Until: 24:00,18",
    )

    # Cooling setpoint (Swedish climate - high setpoint)
    idf.newidfobject(
        "Schedule:Compact",
        Name="CoolingSetpoint",
        Schedule_Type_Limits_Name="Temperature",
        Field_1="Through: 12/31",
        Field_2="For: AllDays",
        Field_3="Until: 24:00,26",
    )

    # ========== MATERIALS ==========
    # Calculate insulation thickness from U-values
    # R = 1/U - Rsi - Rse - Rstructure
    Rsi = 0.13
    Rse = 0.04
    R_structure = 0.15 / 1.7  # 150mm concrete

    R_wall_target = 1 / U_WALL
    R_insul_wall = R_wall_target - Rsi - Rse - R_structure - 0.02/0.8 - 0.013/0.16
    insul_thickness_wall = max(0.05, R_insul_wall * 0.035)

    R_roof_target = 1 / U_ROOF
    R_insul_roof = R_roof_target - Rsi - Rse - R_structure - 0.005/0.19
    insul_thickness_roof = max(0.1, R_insul_roof * 0.035)

    # Wall materials
    idf.newidfobject(
        "Material",
        Name="Plaster",
        Roughness="MediumSmooth",
        Thickness=0.02,
        Conductivity=0.8,
        Density=1600,
        Specific_Heat=840,
    )

    idf.newidfobject(
        "Material",
        Name="Concrete",
        Roughness="MediumRough",
        Thickness=0.15,
        Conductivity=1.7,
        Density=2300,
        Specific_Heat=900,
    )

    idf.newidfobject(
        "Material",
        Name="WallInsulation",
        Roughness="MediumRough",
        Thickness=insul_thickness_wall,
        Conductivity=0.035,
        Density=30,
        Specific_Heat=840,
    )

    idf.newidfobject(
        "Material",
        Name="Gypsum",
        Roughness="Smooth",
        Thickness=0.013,
        Conductivity=0.16,
        Density=800,
        Specific_Heat=1000,
    )

    idf.newidfobject(
        "Material",
        Name="RoofFelt",
        Roughness="Rough",
        Thickness=0.005,
        Conductivity=0.19,
        Density=1100,
        Specific_Heat=1000,
    )

    idf.newidfobject(
        "Material",
        Name="RoofInsulation",
        Roughness="MediumRough",
        Thickness=insul_thickness_roof,
        Conductivity=0.035,
        Density=30,
        Specific_Heat=840,
    )

    # ========== CONSTRUCTIONS ==========
    idf.newidfobject(
        "Construction",
        Name="ExteriorWall",
        Outside_Layer="Plaster",
        Layer_2="Concrete",
        Layer_3="WallInsulation",
        Layer_4="Gypsum",
    )

    idf.newidfobject(
        "Construction",
        Name="Roof",
        Outside_Layer="RoofFelt",
        Layer_2="Concrete",
        Layer_3="RoofInsulation",
    )

    idf.newidfobject(
        "Construction",
        Name="Floor",
        Outside_Layer="Concrete",
    )

    # Window - simple glazing
    idf.newidfobject(
        "WindowMaterial:SimpleGlazingSystem",
        Name="TripleGlazing",
        UFactor=U_WINDOW,
        Solar_Heat_Gain_Coefficient=0.5,
        Visible_Transmittance=0.65,
    )

    idf.newidfobject(
        "Construction",
        Name="Window",
        Outside_Layer="TripleGlazing",
    )

    # ========== ZONE ==========
    zone_name = "WholeBuilding"
    zone_area = FLOOR_AREA
    zone_volume = FLOOR_AREA * FLOOR_HEIGHT  # Average floor height

    idf.newidfobject(
        "Zone",
        Name=zone_name,
        Direction_of_Relative_North=0,
        X_Origin=0,
        Y_Origin=0,
        Z_Origin=0,
        Type=1,
        Multiplier=1,
        Ceiling_Height=FLOOR_HEIGHT,
        Volume=zone_volume,
        Floor_Area=zone_area,
    )

    # ========== SURFACES ==========
    # Floor
    idf.newidfobject(
        "BuildingSurface:Detailed",
        Name="Floor",
        Surface_Type="Floor",
        Construction_Name="Floor",
        Zone_Name=zone_name,
        Outside_Boundary_Condition="Ground",
        Sun_Exposure="NoSun",
        Wind_Exposure="NoWind",
        View_Factor_to_Ground=0,
        Number_of_Vertices=4,
        Vertex_1_Xcoordinate=0, Vertex_1_Ycoordinate=0, Vertex_1_Zcoordinate=0,
        Vertex_2_Xcoordinate=0, Vertex_2_Ycoordinate=DEPTH, Vertex_2_Zcoordinate=0,
        Vertex_3_Xcoordinate=WIDTH, Vertex_3_Ycoordinate=DEPTH, Vertex_3_Zcoordinate=0,
        Vertex_4_Xcoordinate=WIDTH, Vertex_4_Ycoordinate=0, Vertex_4_Zcoordinate=0,
    )

    # Roof
    idf.newidfobject(
        "BuildingSurface:Detailed",
        Name="Roof",
        Surface_Type="Roof",
        Construction_Name="Roof",
        Zone_Name=zone_name,
        Outside_Boundary_Condition="Outdoors",
        Sun_Exposure="SunExposed",
        Wind_Exposure="WindExposed",
        View_Factor_to_Ground=0,
        Number_of_Vertices=4,
        Vertex_1_Xcoordinate=WIDTH, Vertex_1_Ycoordinate=0, Vertex_1_Zcoordinate=BUILDING_HEIGHT,
        Vertex_2_Xcoordinate=WIDTH, Vertex_2_Ycoordinate=DEPTH, Vertex_2_Zcoordinate=BUILDING_HEIGHT,
        Vertex_3_Xcoordinate=0, Vertex_3_Ycoordinate=DEPTH, Vertex_3_Zcoordinate=BUILDING_HEIGHT,
        Vertex_4_Xcoordinate=0, Vertex_4_Ycoordinate=0, Vertex_4_Zcoordinate=BUILDING_HEIGHT,
    )

    # Walls (4 sides)
    walls = [
        ("WallNorth", 0, DEPTH, WIDTH, DEPTH),  # North wall
        ("WallSouth", WIDTH, 0, 0, 0),          # South wall
        ("WallEast", WIDTH, DEPTH, WIDTH, 0),   # East wall
        ("WallWest", 0, 0, 0, DEPTH),           # West wall
    ]

    for wall_name, x1, y1, x2, y2 in walls:
        idf.newidfobject(
            "BuildingSurface:Detailed",
            Name=wall_name,
            Surface_Type="Wall",
            Construction_Name="ExteriorWall",
            Zone_Name=zone_name,
            Outside_Boundary_Condition="Outdoors",
            Sun_Exposure="SunExposed",
            Wind_Exposure="WindExposed",
            View_Factor_to_Ground=0.5,
            Number_of_Vertices=4,
            Vertex_1_Xcoordinate=x1, Vertex_1_Ycoordinate=y1, Vertex_1_Zcoordinate=BUILDING_HEIGHT,
            Vertex_2_Xcoordinate=x1, Vertex_2_Ycoordinate=y1, Vertex_2_Zcoordinate=0,
            Vertex_3_Xcoordinate=x2, Vertex_3_Ycoordinate=y2, Vertex_3_Zcoordinate=0,
            Vertex_4_Xcoordinate=x2, Vertex_4_Ycoordinate=y2, Vertex_4_Zcoordinate=BUILDING_HEIGHT,
        )

    # ========== WINDOWS ==========
    # Add windows to each wall based on WWR
    # Window height = wall height * WWR factor
    # For simplicity, one window per wall spanning most of the width
    window_height = BUILDING_HEIGHT * 0.8 * WWR / 0.3  # Scaled window
    window_height = min(window_height, BUILDING_HEIGHT * 0.7)
    window_bottom = BUILDING_HEIGHT * 0.1

    window_configs = [
        ("WindowNorth", "WallNorth", 0.1*WIDTH, DEPTH, 0.9*WIDTH, DEPTH),
        ("WindowSouth", "WallSouth", 0.1*WIDTH, 0, 0.9*WIDTH, 0),
        ("WindowEast", "WallEast", WIDTH, 0.1*DEPTH, WIDTH, 0.9*DEPTH),
        ("WindowWest", "WallWest", 0, 0.1*DEPTH, 0, 0.9*DEPTH),
    ]

    for win_name, wall_name, x1, y1, x2, y2 in window_configs:
        idf.newidfobject(
            "FenestrationSurface:Detailed",
            Name=win_name,
            Surface_Type="Window",
            Construction_Name="Window",
            Building_Surface_Name=wall_name,
            Outside_Boundary_Condition_Object="",
            View_Factor_to_Ground=0.5,
            Frame_and_Divider_Name="",
            Multiplier=1,
            Number_of_Vertices=4,
            Vertex_1_Xcoordinate=x1, Vertex_1_Ycoordinate=y1, Vertex_1_Zcoordinate=window_bottom + window_height,
            Vertex_2_Xcoordinate=x1, Vertex_2_Ycoordinate=y1, Vertex_2_Zcoordinate=window_bottom,
            Vertex_3_Xcoordinate=x2, Vertex_3_Ycoordinate=y2, Vertex_3_Zcoordinate=window_bottom,
            Vertex_4_Xcoordinate=x2, Vertex_4_Ycoordinate=y2, Vertex_4_Zcoordinate=window_bottom + window_height,
        )

    # ========== INTERNAL LOADS ==========
    # People
    num_people = zone_area / PEOPLE_DENSITY
    idf.newidfobject(
        "People",
        Name=f"{zone_name}_People",
        Zone_or_ZoneList_or_Space_or_SpaceList_Name=zone_name,
        Number_of_People_Schedule_Name="OccupancySchedule",
        Number_of_People_Calculation_Method="People",
        Number_of_People=num_people,
        Fraction_Radiant=0.3,
        Sensible_Heat_Fraction="autocalculate",
        Activity_Level_Schedule_Name="ActivityLevel",
    )

    # Lights
    idf.newidfobject(
        "Lights",
        Name=f"{zone_name}_Lights",
        Zone_or_ZoneList_or_Space_or_SpaceList_Name=zone_name,
        Schedule_Name="LightingSchedule",
        Design_Level_Calculation_Method="Watts/Area",
        Watts_per_Floor_Area=LIGHTING_POWER,
        Fraction_Radiant=0.4,
        Fraction_Visible=0.2,
    )

    # Equipment
    idf.newidfobject(
        "ElectricEquipment",
        Name=f"{zone_name}_Equipment",
        Zone_or_ZoneList_or_Space_or_SpaceList_Name=zone_name,
        Schedule_Name="EquipmentSchedule",
        Design_Level_Calculation_Method="Watts/Area",
        Watts_per_Floor_Area=EQUIPMENT_POWER,
        Fraction_Radiant=0.3,
        Fraction_Latent=0.0,
    )

    # ========== HVAC - IDEAL LOADS (Native Objects) ==========
    # Thermostat setpoint schedules
    idf.newidfobject(
        "ThermostatSetpoint:DualSetpoint",
        Name=f"{zone_name}_DualSetpoint",
        Heating_Setpoint_Temperature_Schedule_Name="HeatingSetpoint",
        Cooling_Setpoint_Temperature_Schedule_Name="CoolingSetpoint",
    )

    # Zone control thermostat
    idf.newidfobject(
        "ZoneControl:Thermostat",
        Name=f"{zone_name}_Thermostat",
        Zone_or_ZoneList_Name=zone_name,
        Control_Type_Schedule_Name="ThermostatControlType",
        Control_1_Object_Type="ThermostatSetpoint:DualSetpoint",
        Control_1_Name=f"{zone_name}_DualSetpoint",
    )

    # Ideal loads air system (native - no ExpandObjects needed)
    idf.newidfobject(
        "ZoneHVAC:IdealLoadsAirSystem",
        Name=f"{zone_name}_IdealLoads",
        Availability_Schedule_Name="AlwaysOn",
        Zone_Supply_Air_Node_Name=f"{zone_name}_SupplyNode",
        Maximum_Heating_Supply_Air_Temperature=50,
        Minimum_Cooling_Supply_Air_Temperature=13,
        Maximum_Heating_Supply_Air_Humidity_Ratio=0.0156,
        Minimum_Cooling_Supply_Air_Humidity_Ratio=0.0077,
        Heating_Limit="NoLimit",
        Cooling_Limit="NoLimit",
        Dehumidification_Control_Type="None",
        Cooling_Sensible_Heat_Ratio=0.7,
        Humidification_Control_Type="None",
    )

    # Zone equipment list
    idf.newidfobject(
        "ZoneHVAC:EquipmentList",
        Name=f"{zone_name}_EquipmentList",
        Load_Distribution_Scheme="SequentialLoad",
        Zone_Equipment_1_Object_Type="ZoneHVAC:IdealLoadsAirSystem",
        Zone_Equipment_1_Name=f"{zone_name}_IdealLoads",
        Zone_Equipment_1_Cooling_Sequence=1,
        Zone_Equipment_1_Heating_or_NoLoad_Sequence=1,
    )

    # Zone equipment connections
    idf.newidfobject(
        "ZoneHVAC:EquipmentConnections",
        Zone_Name=zone_name,
        Zone_Conditioning_Equipment_List_Name=f"{zone_name}_EquipmentList",
        Zone_Air_Inlet_Node_or_NodeList_Name=f"{zone_name}_SupplyNode",
        Zone_Air_Exhaust_Node_or_NodeList_Name="",
        Zone_Air_Node_Name=f"{zone_name}_AirNode",
        Zone_Return_Air_Node_or_NodeList_Name=f"{zone_name}_ReturnNode",
    )

    # ========== OUTPUT ==========
    idf.newidfobject(
        "Output:VariableDictionary",
        Key_Field="Regular",
    )

    idf.newidfobject(
        "Output:Variable",
        Key_Value="*",
        Variable_Name="Zone Ideal Loads Zone Total Heating Energy",
        Reporting_Frequency="Monthly",
    )

    idf.newidfobject(
        "Output:Variable",
        Key_Value="*",
        Variable_Name="Zone Ideal Loads Zone Total Cooling Energy",
        Reporting_Frequency="Monthly",
    )

    idf.newidfobject(
        "Output:Meter",
        Key_Name="Heating:EnergyTransfer",
        Reporting_Frequency="Monthly",
    )

    idf.newidfobject(
        "Output:Meter",
        Key_Name="Cooling:EnergyTransfer",
        Reporting_Frequency="Monthly",
    )

    idf.newidfobject(
        "OutputControl:Table:Style",
        Column_Separator="Comma",
        Unit_Conversion="JtoKWH",
    )

    idf.newidfobject(
        "Output:Table:SummaryReports",
        Report_1_Name="AllSummary",
    )

    return idf


def main():
    from rich.console import Console
    console = Console()

    console.print("\n[bold cyan]═══ EnergyPlus IDF Generator ═══[/bold cyan]\n")

    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Generate IDF using string-based approach (more reliable)
    console.print("Creating IDF...")
    idf_content = create_idf_string()

    # Save
    output_path = OUTPUT_DIR / "sjostaden_base.idf"
    with open(output_path, 'w') as f:
        f.write(idf_content)
    console.print(f"[green]✓ Saved: {output_path}[/green]")

    # Print summary
    console.print(f"\n[bold]Building Parameters:[/bold]")
    console.print(f"  Floor area: {FLOOR_AREA:,} m²")
    console.print(f"  Building height: {BUILDING_HEIGHT} m ({NUM_FLOORS} floors)")
    console.print(f"  U-wall: {U_WALL} W/m²K")
    console.print(f"  U-roof: {U_ROOF} W/m²K")
    console.print(f"  U-window: {U_WINDOW} W/m²K")
    console.print(f"  WWR: {WWR_AVG*100:.0f}%")

    # Find weather file
    weather_files = list(WEATHER_DIR.glob("*Stockholm*"))
    if weather_files:
        console.print(f"\n[bold]Weather file found:[/bold]")
        console.print(f"  {weather_files[0].name}")
        weather_path = weather_files[0]
    else:
        # Try to find any Swedish weather file
        weather_files = list(WEATHER_DIR.glob("SWE_*.epw"))
        if weather_files:
            weather_path = weather_files[0]
            console.print(f"\n[bold]Weather file found:[/bold]")
            console.print(f"  {weather_path.name}")
        else:
            console.print("\n[yellow]No Swedish weather file found in EnergyPlus installation[/yellow]")
            weather_path = None

    # Print run command
    console.print(f"\n[bold]To run simulation:[/bold]")
    if weather_path:
        console.print(f"  energyplus -w {weather_path} -d {OUTPUT_DIR} {output_path}")
    else:
        console.print(f"  energyplus -d {OUTPUT_DIR} {output_path}")
        console.print("  (Note: Download Swedish weather file from energyplus.net)")

    return output_path, weather_path


if __name__ == "__main__":
    main()
